from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

from bio_mcp.cache.schema import CacheDocument


def load_cache(path: Path) -> CacheDocument:
    """
    Load a cached CVMFS inventory document from disk.

    This function assumes the cache was generated by build_cache.py
    and does not attempt to rebuild or validate it.
    """
    if not path.exists():
        raise FileNotFoundError(f"Cache file not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        data: Dict[str, Any] = json.load(f)

    return data
